### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by username7171** [washim/python-elastic-logstash#1]
hi, your tool seems really interesting

However, the ELK tutorials on various websites often don't cover python.

So if  I just plainly use python logging in some scripts without any web application, there is no need to configure logstash ?

Just append the handler of elastic search to python logger?

**Comment by washim** [comment]
You absolutely right. Logstash is not required if using python. Logstash has its own rule to handle the same. I faced challenge with logstash for critical ETL pipeline due to high learning curve hence invented this library.
