### ISSUE TITLE
In case of disconnection of the elasticsearch server the logger slows down and even crash the entire process

### ISSUE THREAD

**Issue by itshakh** [washim/python-elastic-logstash#2]

**Comment by washim** [comment]
I need more information or how I will reproduce this. Better if you have screenshot of error.

**Comment by mohammadalgunaid** [comment]
1. Up elasticsearch in docker container
2. Run app with logger (python-elastic-logstash)
3. Down elasticsearch in docker container

Messages: `Unable to connect elastic host. Logstash will restore when available.`

Logger slows down

**Comment by kirill20123456** [comment]
Up elasticsearch in docker container
Run app with logger (python-elastic-logstash)
Down elasticsearch in docker container
Messages: Unable to connect elastic host. Logstash will restore when available.

Logger slows down
